# Sample information
samples:
  pbmc3k:
    min_genes: 200
    max_genes: 2500
    max_mt_percent: 5
    min_cells: 3
  pbmc8k:
    min_genes: 200
    max_genes: 2500
    max_mt_percent: 5
    min_cells: 3